### ISSUE TITLE
wow

### ISSUE THREAD

**Issue by prazedotid** [andraantariksa/sunda-lang#1]
rust kh

**Comment by randspace0** [comment]
rust pke gc

**Comment by randspace0** [comment]
Yang jelas ga pake borrow system, karena terlalu susah. Tapi konsep-konsep sama sintaks banyak terinspirasi rust

**Comment by prazedotid** [comment]
naha syntaxna teu ngangge basa sunda

**Comment by randspace0** [comment]
basa java oge teu ngangge basa jawa

**Comment by prazedotid** [comment]
siap akang jago
